

"""
Author: Dream Team
Program: encoder.py
Date: 2025
"""

#!/usr/bin/env python3
"""
Encoder for eCTF Satellite Frames with HMAC-SHA256
This module encodes frames by constructing a header, appending the frame data,
and adding an HMAC-SHA256 signature for authentication.
Maximum frame size is 64 bytes.
"""

import argparse
import struct
import json
import binascii
import hmac
import hashlib

class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """
        # Parse the JSON secrets file
        secrets = json.loads(secrets)
        # Load the example secret for use in Encoder.encode
        self.some_secrets = secrets["some_secrets"]
        # Precompute the HMAC key from the secret (16 bytes expected)
        self.hmac_key = binascii.unhexlify(self.some_secrets)
        if len(self.hmac_key) != 16:
            raise ValueError("HMAC key must be 16 bytes long")

    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        :param channel: 32b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """
        if len(frame) > 64:
            raise ValueError("Frame length exceeds maximum allowed 64 bytes")
        # Pack header: channel (4 bytes) and timestamp (8 bytes) in little-endian
        header = struct.pack("<IQ", channel, timestamp)
        # Construct payload: header + frame
        payload = header + frame
        # Compute HMAC-SHA256 signature over the payload
        signature = hmac.new(self.hmac_key, payload, hashlib.sha256).digest()
        # Return the complete packet: payload followed by signature
        return payload + signature

def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()
    encoder = Encoder(args.secrets_file.read())
    encoded = encoder.encode(args.channel, args.frame.encode(), args.timestamp)
    print(repr(encoded))

if __name__ == "__main__":
    main()

